name: Reusable SQL Deployment

on:
  workflow_call:

    inputs:

      deployment_name:
        required: true
        type: string

      sql_file:
        required: true
        type: string

      runner:
        required: true
        type: string

      environment:
        required: true
        type: string

    secrets:

      SQL_USER:
        required: true

      SQL_PASSWORD:
        required: true

      TEAMS_WEBHOOK:
        required: true

      SQL_SERVER:
        required: true

      SQL_DATABASE:
        required: false


jobs:


  deploy:

    runs-on: ${{ inputs.runner }}

    environment: ${{ inputs.environment }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      # --------------------------------
      # WINDOWS CHECK
      # --------------------------------
      - name: Verify sqlcmd Installation (Windows)
        if: ${{ inputs.runner == 'windows-latest' }}
        shell: pwsh
        run: |
          sqlcmd -?

      # =========================
      # START NOTIFICATION
      # =========================
      - name: Send Remote Deployment Request
        shell: pwsh
        run: |
          @body = @ {
            text = "🟡 LOCAL/REMOTE DEPLOYMENT REQUEST 🟡`n`nDatabase is ready for deployment to partner SQL Server. `n`n👉 Review here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
          } | ConvertTo-Json

          Invoke-RestMethod `
           -Uri "${{ secrets.TEAMS_WEBHOOK }}" `
           -Method Post `
           -ContentType "application/json" `
           -Body $body


      # =========================
      # DEPLOY (WINDOWS)
      # =========================
      - name: Deploy Database (Windows)
        if: ${{ inputs.runner == 'windows-latest' }}
        shell: pwsh
        run: |
          sqlcmd `
            -S "${{ secrets.SQL_SERVER }}" `
            -d "${{ secrets.SQL_DATABASE }}" `
            -U "${{ secrets.SQL_USER }}" `
            -P "${{ secrets.SQL_PASSWORD }}" `
            -C `
            -i "${{ inputs.sql_file }}"

      # =========================
      # SUCCESS
      # =========================

      - name: Remote Deployment Success
        if: success()
        shell: pwsh
        run: |
          $body = @{
           text = "🟢 REMOTE DEPLOYMENT SUCCESS 🟢`n`nDatabase deployed to partner SQL Server successfully.`n`nRun ID: ${{ github.run_id }}"
          } | ConvertTo-Json

          Invoke-RestMethod `
           -Uri "${{ secrets.TEAMS_WEBHOOK }}" `
           -Method Post `
           -ContentType "application/json" `
           -Body $body


      # =========================
      # FAILURE
      # =========================
      - name: Remote Deployment Failure
        if: failure()
        shell: pwsh
        run: |
          $body = @{
            text = "🔴 REMOTE DEPLOYMENT FAILED 🔴`n`nPartner deployment failed.`n`nRun ID: ${{ github.run_id }}"
          } | ConvertTo-Json

          Invoke-RestMethod `
           -Uri "${{ secrets.TEAMS_WEBHOOK }}" `
           -Method Post `
           -ContentType "application/json" `
           -Body $body