name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 

      - name: Install dependencies
        working-directory: "GitHub Actions Course/GitHub Actions/04+Practice+Project+(Start)/04 Practice Project"
        run: npm ci

      - name: Lint
        working-directory: "GitHub Actions Course/GitHub Actions/04+Practice+Project+(Start)/04 Practice Project"
        run: npm run lint

      - name: Build code
        working-directory: "GitHub Actions Course/GitHub Actions/04+Practice+Project+(Start)/04 Practice Project"
        run: npm run build
        
      - name: Deploy code
        run: echo "Deploying..."
