name: Deploy Project

on: [push, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: "GitHub Actions Course/GitHub Actions/02+Starting+Project/02 Starting Project"
        run: npm ci

      - name: Run tests
        working-directory: "GitHub Actions Course/GitHub Actions/02+Starting+Project/02 Starting Project"
        run: npm test
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: "GitHub Actions Course/GitHub Actions/02+Starting+Project/02 Starting Project"
        run: npm ci
      
      - name: Build project
        run: npm run build
        working-directory: "GitHub Actions Course/GitHub Actions/02+Starting+Project/02 Starting Project"

      - name: Deploy
        run: echo "Deploying..."
                    
