name: GitHub-MS Teams Events Integration

on:
  push:
  pull_request:
    types: [opened, review_requested, closed]
  pull_request_review:
    types: [submitted]
  create: 

jobs:
  notify-teams:
    runs-on: ubuntu-latest

    steps:
    - name: Send message to MS Teams
      run: |
        EVENT_NAME="${{ github.event_name }}"

        if [ "$EVENT_NAME" = "push" ]; then
        MESSAGE="🛫 Push event in ${{ github.repository }}

By: ${{ github.actor }}

Commit: ${{ github.event.head_commit.message }}

Link: ${{ github.event.head_commit.url }}"

    elif [ "$EVENT_NAME" = "create" ] && [ "${{ github.event.ref_type }}" = "branch" ]; then
      MESSAGE="A new Branch was created in ${{ github.repository }}

Branch: ${{ github.event.ref }}

By: ${{ github.actor }}

Link: https://github.com/${{ github.repository }}/tree/${{ github.event.ref }}"

    elif [ "$EVENT_NAME" = "pull_request" ] && [ "${{ github.event.action }}" = "opened" ]; then
      MESSAGE="A Pull Request was Created in ${{ github.repository }}

By: ${{ github.actor }}

Title: ${{ github.event.pull_request.title }}

Link: ${{ github.event.pull_request.html_url }}"

    elif [ "$EVENT_NAME" = "pull_request" ] && [ "${{ github.event.action }}" = "review_requested" ]; then
      MESSAGE=" Approval Requested in ${{ github.repository }}

By: ${{ github.event.pull_request.user.login }}

Reviewer: ${{ github.event.requested_reviewer.login }}

Status: Review Requested

Link: ${{ github.event.pull_request.html_url }}"

    elif [ "$EVENT_NAME" = "pull_request" ] && [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
      MESSAGE="Pull Request Merged in ${{ github.repository }}

Merged By: ${{ github.actor }}

Title: ${{ github.event.pull_request.title }}

Link: ${{ github.event.pull_request.html_url }}"

    elif [ "$EVENT_NAME" = "pull_request_review" ] && [ "${{ github.event.review.state }}" = "approved" ]; then
      MESSAGE="🛬 Pull Request approved in ${{ github.repository }}

Approved By: ${{ github.actor }}"

    else
      exit 0
    fi

    curl -H "Content-Type: application/json" \
      -d "{\"text\":\"$MESSAGE\"}" \
      "${{ secrets.TEAMS_WEBHOOK }}"