name: GitHub-MS Teams Events Integration

on: [push, pull_request, create]


jobs:
  notify-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to MS Teams
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "text": "🚀 New commit pushed to *main* branch in ${{ github.repository }} by ${{ github.actor }}.\n\nCommit message: ${{ github.event.head_commit.message }}\n\n🔗 View: ${{ github.event.head_commit.url }}"
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

    

