name: Local Deployment

on:
  workflow_dispatch:

jobs:

  Dev:
    uses: ./.github/workflows/db-tunnel-template.yml

    with:
      deployment_name: LOCAL DEPLOYMENT
      runner: ubuntu-latest
      sql_file: ${{ vars.SQL_SCRIPT_PATH }}
      environment: ${{ vars.LOCAL_ENVIRONMENT }}
      

    secrets:
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
      SQL_SERVER: ${{ secrets.SQL_SERVER }}