name: Remote Deployment

on:
  push:

jobs:

  Production:
    
    uses: ./.github/workflows/db-tunnel-template.yml
    

    with:
      deployment_name: REMOTE DEPLOYMENT
      runner: ubuntu-latest
      sql_file: ${{ vars.SQL_SCRIPT_PATH }}
      environment: ${{ vars.REMOTE_ENVIRONMENT }}

    secrets:
      SQL_USER: ${{ secrets.RUSHIL_SQL_USER }}
      SQL_PASSWORD: ${{ secrets.RUSHIL_SQL_PASSWORD }}
      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
      SQL_SERVER: ${{ secrets.RUSHIL_SQL_SERVER }}
      SQL_DATABASE: ${{ secrets.RUSHIL_SQL_DATABASE }}

  