name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        working-directory: "GitHub Actions Course/GitHub Actions/Section 7 Project/01 Starting Project"
        run: npm ci

      - name: Build project
        working-directory: "GitHub Actions Course/GitHub Actions/Section 7 Project/01 Starting Project"
        run: npm run build