name: Deploy SSIS Timesheet Project

on:
  push:
    #branches:
    #  - main

  #workflow_dispatch:

env:
  SQL_SCRIPT: "./Timesheet-Project/Deploy-Databases.sql"
  SSIS_JOB_SCRIPT: "./Timesheet-Project/Run-SSIS-Job.sql"

jobs:

  deploy:

    runs-on: windows-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Verify sqlcmd Installation
      shell: pwsh
      run: |
        sqlcmd -?

    - name: Deploy Database
      shell: pwsh
      run: |
        sqlcmd `
          -S "${{ secrets.SQL_SERVER }}" `
          -U "${{ secrets.SQL_USER }}" `
          -P "${{ secrets.SQL_PASSWORD }}" `
          -C `
          -i "${{ env.SQL_SCRIPT }}" 
        
        

    - name: Run SSIS Job
      shell: pwsh
      run: |
        sqlcmd `
          -S "${{ secrets.SQL_SERVER }}" `
          -U "${{ secrets.SQL_USER }}" `
          -P "${{ secrets.SQL_PASSWORD }}" `
          -C `
          -i "${{ env.SSIS_JOB_SCRIPT }}" 
        

    - name: Verify Deployment
      shell: powershell
      run: |
        echo "Deployment Complete"