name: DB-Cloud-Tunnel-LM

on:
  push:
    
jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install SQL tools
      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev

      #3. Tests Connectivity
      - name: Test connectivity first
        run: |
          /opt/mssql-tools/bin/sqlcmd \
            -S ${{ secrets.SQL_HOST }},${{ secrets.SQL_PORT }} \
            -U ${{ secrets.SQL_USER }} \
            -P ${{ secrets.SQL_PASSWORD }} \
            -Q "SELECT @@VERSION"

      # 4. Run SQL script against remote SQL Server via Pinggy
      - name: Execute SQL script
        env:
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_PORT: ${{ secrets.SQL_PORT }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          /opt/mssql-tools/bin/sqlcmd \
            -S ${SQL_HOST},${SQL_PORT} \
            -U ${SQL_USER} \
            -P ${SQL_PASSWORD} \
            -i /DB-Cloud-Tunnel-LM/SQL-Deployment-Script.sql